### ISSUE TITLE
请问下买单的接口不能调用吗？

### ISSUE THREAD

**Issue by 496087321** [Dragonexio/OpenApi#1]
请问接口11.下买单不能调用吗？ 调用返回400错误！

**Comment by haichong01** [comment]
可以用，检查下金额精度  部分币种只有4位

**Comment by Dragonexio** [comment]
调试问题建议到我们的官方API讨论群咨询：https://t.me/DragonEx_API
同时，最好能有更多的信息，比如语言、环境、或部分代码片段，以便技术人员判断问题所在
