### ISSUE TITLE
the method with params  invoding the get of http such as getMarketBuy in nodeJs demo not work

### ISSUE THREAD

**Issue by archangellcc** [Dragonexio/OpenApi#2]
getMarketLine(symbolID, startTime, searchDirection, count, klineType) {
		let path = "/api/v1/market/kline/";
		let params = {
			'symbol_id': symbolID,
			'st': startTime,
			'direction': searchDirection,
			'count': count,
            'kline_type': klineType
		};
		return this.sendGET(path, params, null);
	}

    sendGET(path, params, headers) {
        return new Promise((resolve, reject) => {
            let url = this.getURL(path); 
            if (params !== null)
                url += "?" + params;
     ......

the url will not be "http://xxxx?xxx&xxx&xxx" but “https://openapi.dragonex.im/api/v1/market/kline/?[object Object]'”.

**Comment by Dragonexio** [comment]
Thank you for your submission, we have just resolved the bug. You can pull the lasted example.
